### ISSUE TITLE
ESM library has no default export

### ISSUE THREAD

**Issue by ZeeCapp** [eway-crm/js-lib#18]
Hi,

i recently tried to use this library to connect to eway, but i ran into an issue. I used the example code from README as a basis, but i noticed that it didn't work. I did some digging and i found out that typescript thinks the ESM version of the library has a default export, however this is not the case at runtime. The folowing code throws:

```js
//example code coppied from README.md
import ApiConnection from '@eway-crm/connector'; 

const serviceUrl = 'https://trial.eway-crm.com/31994';
const username = 'api';
const passwordHash = '470AE7216203E23E1983EF1851E72947';

//no error at compile time with typescript, but throws at runtime with error:
// TypeError: ApiConnections.create is not a function
const connection = ApiConnection.create(serviceUrl, username, passwordHash, 'JSSample1', '00:00:00:00:00', 'SampleTestMachine', (err) => console.error(err));
```

When you change the first line to
```js
import { ApiConnectionAsNonDefaultExport as ApiConnection } from '@eway-crm/connector';
```
the code works.

The issue is probably caused by Rollup removing the default export for the ESM version during the build. When i try to build the library from source, Rollup throws the following warning:
```
(!) Mixing named and default exports
https://rollupjs.org/configuration-options/#output-exports
The following entry modules are using named and default exports together:
src/index.ts
```

The solution is probably to only use named exports instead of mixing named and default exports, as per rollup's docs: https://rollupjs.org/configuration-options/#output-exports

**Comment by havri** [comment]
Hello Jan,

thank you for your feedback and the resoluton.
We are aware of this issue. The reason for the mixed exports is backward compatibility of the CommonJS output. The solution with consolidated exports will be a breaking change, but it is planned to be done. As a temporary workarround we added the mentioned `ApiConnectionAsNonDefaultExport`. We are glad you have found it.

Best regards

Stepan
Team eWay-CRM
